// This file is automatically generated and contains assets from base-goerli.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0xf0d799E4600FF12ce3c4cdd67F8F460e7dF1eFea');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xf0d799E4600FF12ce3c4cdd67F8F460e7dF1eFea'), // USDC
  ],
  pricingAssets: [
    Address.fromString('0x4200000000000000000000000000000000000006'), // ETH
    Address.fromString('0x243CAf595F57005e6A067645FeE1e5c1Cdbc60a2'), // BTCB
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
